### ISSUE TITLE
Project proposal

### ISSUE THREAD

**Issue by zhangyin-github** [cihatkececi/ChannelCodingProjectList#3]
Hi! We have just updated our channel coding toolkit.
We wonder if our toolkit could be added to your list.
The toolkit could be found at https://github.com/zhangyin-github/ppcode3
Thanks!

**Comment by cihatkececi** [comment]
Thank you for the recommendation. I've added the toolkit to the list.

**Comment by zhangyin-github** [comment]
Thanks a lot!
